### ISSUE TITLE
关于 Assistant 的完整使用流程

### ISSUE THREAD

**Issue by whhdxl** [levie-vans/WeChatAssistant-ForMac#1]
请教老师，一方面在 md 中有说到要使用原版微信，不对其进行修改，但另一方面小助手本身安装完成后需要重签才能运行，如何改变第一点呢？

我有做过以下尝试：

- 完整官方包+微信小助手安装后不重签 + Assistant 启动-- 这种方式下启动的微信并没有成功加载小助手；
- 完整官方包+ Assistant 启动 -- 同样的也没有成功加载小助手；
- 安装小助手后 + 重签+Assistant 启动 -- 能够重新加载小助手，但感觉没有规避老师 md 中第一点。

所以老师能详细说说安装方式吗？

**Comment by levie-vans** [comment]
不用安装，启动WeChat Assistant.app，它会自动设置DYLD_INSERT_LIBRARIES这个环境变量，然后再启动微信，这时候登录成功就是已经包含小助手的了，但是使用的还是官方未修改的微信。

**Comment by iszhuzhi** [comment]
前来膜拜老师

**Comment by BruceChao** [comment]
请问小助手和微信都使用最新版的情况下，也能正常使用吗？

**Comment by qiuyulcc** [comment]
> 官方微信正常安装，放进/Applications/目录，不是直接启动微信，是启动WeChat Assistant.app，它会自动设置DYLD_INSERT_LIBRARIES这个环境变量，然后自动启动微信，这时候登录成功就是已经包含小助手的了，但是使用的还是官方未修改的微信。
> 
> 可能需要重签WeChat Assistant.app，可能是因为我使用的小助手是我本机重签过的。重签WeChat Assistant.app不影响微信的签名，所以放心使用。

codesign --force --deep --sign - /Applications/WeChat\ Assistant.app/
提示 /Applications/WeChat Assistant.app/: resource fork, Finder information, or similar detritus not allowed  签名好像不成功

**Comment by liushawulan** [comment]
xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。

**Comment by liushawulan** [comment]
就需要一个自动登录功能。偶尔打开电脑版时就不需要拿起手机了。

**Comment by qiuyulcc** [comment]
> xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。

我也是了你的签名方式  好像还是不行- -

**Comment by levie-vans** [comment]
> > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> 
> 我也是了你的签名方式 好像还是不行- -

那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &

**Comment by qiuyulcc** [comment]
> > > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> > 
> > 
> > 我也是了你的签名方式 好像还是不行- -
> 
> 那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
> nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &

执行了   直接打开了微信  但是登录上助手没有载入=  = 不知道是哪里出现了问题

**Comment by qiuyulcc** [comment]
> > > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> > 
> > 
> > 我也是了你的签名方式 好像还是不行- -
> 
> 那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
> nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &

关闭sip就OK了

**Comment by qiuyulcc** [comment]
> > > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> > 
> > 
> > 我也是了你的签名方式 好像还是不行- -
> 
> 那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
> nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &

不过  好像你打包的小助手不是最新版本？  我不知道怎么替换成最新的2.9.2版本的小助手

**Comment by levie-vans** [comment]
> > > > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> > > 
> > > 
> > > 我也是了你的签名方式 好像还是不行- -
> > 
> > 
> > 那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
> > nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &
> 
> 不过 好像你打包的小助手不是最新版本？ 我不知道怎么替换成最新的2.9.2版本的小助手

我记得是最新2.9.2版

**Comment by levie-vans** [comment]
> > > > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> > > 
> > > 
> > > 我也是了你的签名方式 好像还是不行- -
> > 
> > 
> > 那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
> > nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &
> 
> 不过 好像你打包的小助手不是最新版本？ 我不知道怎么替换成最新的2.9.2版本的小助手

**DYLD_INSERT_LIBRARIES需要关闭系统的SIP，如果使用此方法，请自行关闭SIP。**

**Comment by qiuyulcc** [comment]
> > > > > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> > > > 
> > > > 
> > > > 我也是了你的签名方式 好像还是不行- -
> > > 
> > > 
> > > 那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
> > > nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &
> > 
> > 
> > 不过 好像你打包的小助手不是最新版本？ 我不知道怎么替换成最新的2.9.2版本的小助手
> 
> 我记得是最新2.9.2版

我加载了小助手后    打开微信就提示我小助手需要更新= = 然后更新了  其实是更新不成功的=  =

**Comment by levie-vans** [comment]
> > > > > > xattr -cr <path_to_app_bundle> 重签名成功，但是小助手启动不了。
> > > > > 
> > > > > 
> > > > > 我也是了你的签名方式 好像还是不行- -
> > > > 
> > > > 
> > > > 那你试试手动，在终端里执行export DYLD_INSERT_LIBRARIES=改名后的小助手路径&&
> > > > nohup /Applications/WeChat.app/Contents/MacOS/WeChat > /tmp/wechat.txt 2>&1 &
> > > 
> > > 
> > > 不过 好像你打包的小助手不是最新版本？ 我不知道怎么替换成最新的2.9.2版本的小助手
> > 
> > 
> > 我记得是最新2.9.2版
> 
> 我加载了小助手后 打开微信就提示我小助手需要更新= = 然后更新了 其实是更新不成功的= =

实际上已经是最新版了，提示有误。另外更新是原来插件的更新功能，肯定是无法更新的。
