### ISSUE TITLE
mac os 最新系统无法打开微信= =  希望作者能抽空解决下  谢谢

### ISSUE THREAD

**Issue by qiuyulcc** [levie-vans/WeChatAssistant-ForMac#13]

**Comment by levie-vans** [comment]
我猜是没关sip，你关了试试

**Comment by qiuyulcc** [comment]
> 我猜是没关sip，你关了试试

我来试试  谢谢

**Comment by qiuyulcc** [comment]
> 我猜是没关sip，你关了试试

不行= =  关了sip还是不行  打开小助手就是弹一下就没反应了 = =

**Comment by levie-vans** [comment]
> > 我猜是没关sip，你关了试试
> 
> 不行= = 关了sip还是不行 打开小助手就是弹一下就没反应了 = =

那等我升级完12回来先

**Comment by levie-vans** [comment]
已更新Alfred插件，支持macOS 12。
