### ISSUE TITLE
codesign --force --deep --sign - /Applications/WeChat\ Assistant.app/  报错

### ISSUE THREAD

**Issue by zhuweideng** [levie-vans/WeChatAssistant-ForMac#5]
codesign --force --deep --sign - /Applications/WeChat\ Assistant.app/
提示 /Applications/WeChat Assistant.app/: resource fork, Finder information, or similar detritus not allowed

**Comment by levie-vans** [comment]
xattr -rc

**Comment by BruceChao** [comment]
我始终不行。微信3.1.5需要使用旧版本嘛？

**Comment by levie-vans** [comment]
> 我始终不行。微信3.1.5需要使用旧版本嘛？

我使用的是最新版

**Comment by qiuyulcc** [comment]
> > 我始终不行。微信3.1.5需要使用旧版本嘛？
> 
> 我使用的是最新版

at\ Assistant.app/
xattr: No such file: codesign
xattr: No such file: --force
xattr: No such file: --deep
xattr: No such file: --sign
xattr: No such file: -同样显示签不了名= =  我给文件重新签了名  但是好像还不行  小助手没办法载入

**Comment by levie-vans** [comment]
> 我始终不行。微信3.1.5需要使用旧版本嘛？

关闭SIP才行
