### ISSUE TITLE
为啥用这个启动之后，聊天记录是从2月份开始的呢？难道电脑里有2个版本的微信吗。。。

### ISSUE THREAD

**Issue by F5F5** [levie-vans/WeChatAssistant-ForMac#8]
直接打开微信.app的话，聊天记录是最新的

**Comment by jiaonisi** [comment]
> 直接打开微信.app的话，聊天记录是最新的

是的，我也有这个问题，不知道咋解决

**Comment by levie-vans** [comment]
这是因为使用DYLD_INSERT_LIBRARIES注入微信进程后，微信的沙盒环境实际上是被破坏的，不能再访问之前官方微信使用的沙盒里的内容。

**Comment by qeq66** [comment]
同问，，那聊天记录怎么迁移过来呢

**Comment by levie-vans** [comment]
已更新Alfred插件，支持macOS 12。
新版新增启动带小助手官方微信模式，这个模式的聊天记录和官方微信就是同步的了。

**Comment by specp** [comment]
> 已更新Alfred插件，支持macOS 12。 新版新增启动带小助手官方微信模式，这个模式的聊天记录和官方微信就是同步的了。

请问是哪个选项和官方版共通数据？官方版登录了的情况下，执行脚本还是会跟启动器一样，是作为新环境，需要扫码登录。
<img width="347" alt="截屏2021-11-13 19 33 59" src="https://user-images.githubusercontent.com/63186513/141642274-4f56bd48-910d-4300-bfc3-fdd10a893fb7.png">

**Comment by levie-vans** [comment]
> > 已更新Alfred插件，支持macOS 12。 新版新增启动带小助手官方微信模式，这个模式的聊天记录和官方微信就是同步的了。
> 
> 请问是哪个选项和官方版共通数据？官方版登录了的情况下，执行脚本还是会跟启动器一样，是作为新环境，需要扫码登录。 <img alt="截屏2021-11-13 19 33 59" width="347" src="https://user-images.githubusercontent.com/63186513/141642274-4f56bd48-910d-4300-bfc3-fdd10a893fb7.png">

第一个，微信版本3.1x

**Comment by specp** [comment]
> > > 已更新Alfred插件，支持macOS 12。 新版新增启动带小助手官方微信模式，这个模式的聊天记录和官方微信就是同步的了。
> > 
> > 
> > 请问是哪个选项和官方版共通数据？官方版登录了的情况下，执行脚本还是会跟启动器一样，是作为新环境，需要扫码登录。 <img alt="截屏2021-11-13 19 33 59" width="347" src="https://user-images.githubusercontent.com/63186513/141642274-4f56bd48-910d-4300-bfc3-fdd10a893fb7.png">
> 
> 第一个，但它只能作为第一个启动的微信，不能启用一个官方微信后再用这个。

可我把资源库里的微信文件夹整个搬走的情况下（等于登陆数据全没了吧），只用你说的这个选项开启一个微信。登录，关闭微信，然后直接开官方微信，一样也是提示需要扫码诶。我还专门去看了数据路径，仍然是
～/Library/Containers/微信/Data/Library/Containers/微信/Data/

然后我想问一下，readme里更新的真的是有效路径吗？官方微信从来没使用过直属于～/Library下面的Application Supports

**Comment by specp** [comment]
我还是好困惑，不清楚为什么你发的跟我自己实际情况差别这么大。

我自己正常使用官方微信，微信的聊天数据的路径是
~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/

之前用独立启动器和现在用Alfred时，数据路径是
~/Library/Containers/com.tencent.xinWeChat/Data/Library/**Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/**
整个容器路径在微信的资源库内嵌套了一次

3.1、3.2都是如此。

**Comment by levie-vans** [comment]
> > > > 已更新Alfred插件，支持macOS 12。 新版新增启动带小助手官方微信模式，这个模式的聊天记录和官方微信就是同步的了。
> > > 
> > > 
> > > 请问是哪个选项和官方版共通数据？官方版登录了的情况下，执行脚本还是会跟启动器一样，是作为新环境，需要扫码登录。 <img alt="截屏2021-11-13 19 33 59" width="347" src="https://user-images.githubusercontent.com/63186513/141642274-4f56bd48-910d-4300-bfc3-fdd10a893fb7.png">
> > 
> > 
> > 第一个，但它只能作为第一个启动的微信，不能启用一个官方微信后再用这个。
> 
> 可我把资源库里的微信文件夹整个搬走的情况下（等于登陆数据全没了吧），只用你说的这个选项开启一个微信。登录，关闭微信，然后直接开官方微信，一样也是提示需要扫码诶。我还专门去看了数据路径，仍然是 ～/Library/Containers/微信/Data/Library/Containers/微信/Data/
> 
> 然后我想问一下，readme里更新的真的是有效路径吗？官方微信从来没使用过直属于～/Library下面的Application Supports

用第一个，数据所在位置和官方微信相同

**Comment by levie-vans** [comment]
> 我还是好困惑，不清楚为什么你发的跟我自己实际情况差别这么大。
> 
> 我自己正常使用官方微信，微信的聊天数据的路径是 ~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/
> 
> 之前用独立启动器和现在用Alfred时，数据路径是 ~/Library/Containers/com.tencent.xinWeChat/Data/Library/**Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/** 整个容器路径在微信的资源库内嵌套了一次
> 
> 3.1、3.2都是如此。

官方微信是~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/
用启动器或者双开，用的是nohup 启动，这样启动的话，就是那样的。

**Comment by specp** [comment]
> > 我还是好困惑，不清楚为什么你发的跟我自己实际情况差别这么大。
> > 我自己正常使用官方微信，微信的聊天数据的路径是 ~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/
> > 之前用独立启动器和现在用Alfred时，数据路径是 ~/Library/Containers/com.tencent.xinWeChat/Data/Library/**Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/** 整个容器路径在微信的资源库内嵌套了一次
> > 3.1、3.2都是如此。
> 
> 官方微信是~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/ 用启动器或者双开，用的是nohup 启动，这样启动的话，就是那样的。

不是啊。我是你发的alfred 1.1，启动的第一个。非双开带助手的那个啊。走的时nohup一个数据路径。真跟官方原版不一样，哭了
